### ISSUE TITLE
vendor folder

### ISSUE THREAD

**Issue by vignemail1** [calmip/gramc3#2]
## Description

Le dossier `vendor` est normalement généré par `composer` suivant ce qui est écrit dans les fichiers `composer.json` (qui décrit les dépendances de l'applications avec les versions utilisables en suivant la SemVer de `composer` ainsi que d'autres éléments comme des alias de scripts) et `composer.lock` (versions des modules qui ont été testés et conformes avec les versions spécifiées dans `composer.json`).

## Problème

Le dossier `vendor` n'a, à priori, pas besoin d'être peuplé dans le dépôt git car il doit être 100% reconstructible depuis le contenu des deux fichiers `composer.*` qui décrivent les dépendances pour l'application.

## Proposition de solution 

- Supprimer le contenu du dossier `vendor`
- Ajouter une exclusion du contenu du dossier `vendor` dans un fichier `.gitignore` à la base du projet
- Documenter qu'il faut lancer une commande `composer install` après le `git clone` afin de récupérer les dépendances

**Comment by vignemail1** [comment]
Recommendation de composer sur le sujet : https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

**Comment by calmip** [comment]
OK vendor n'est plus dans le dépôt (branche develop)
