### ISSUE TITLE
Exception raised when no session exists

### ISSUE THREAD

**Issue by vignemail1** [calmip/gramc3#7]
## Description du problème

Contexte: Version de gramc v3: feature/criann

Lors de la première utilisation des différents menus du mode Administrateur, alors qu'aucune session n'a été créée, des Exceptions sont remontées.
Lorsque l'on cliques sur "Projets ( par session )" on obtient le message suivant 

```
Error:
Call to a member function getIdSession() on null

  at src/Controller/ProjetController.php:862
  at App\Controller\ProjetController->sessionAction()
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:66)                
```

```
Error
in src/Controller/ProjetController.php (line 862)
            'nombreTermine'       => $nombreTermine,
            'nombreAnnule'        => $nombreAnnule,
            'nombreEditionFil'    => $nombreEditionFil,
            'nombreExpertiseFil'  => $nombreExpertiseFil,
            'form'                => $form->createView(), // formulaire 
            'idSession'           => $session->getIdSession(), // formulaire
            'session'             => $session,
            'versions'            => $versions,
            'versions_suppl'      => $versions_suppl,
            'nombreNouveaux'      => $nombreNouveaux,
            'demHeures'           => $demHeures,
in vendor/symfony/http-kernel/HttpKernel.php -> sessionAction (line 158)
in vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 80)
in vendor/symfony/http-kernel/Kernel.php -> handle (line 201)
Kernel->handle()
in public/index.php (line 66)
```

Level | Channel | Message
-- | -- | --
INFO10:13:09 | request | Matched route "projet_session".{     "route": "projet_session",     "route_parameters": {         "_route": "projet_session",         "_controller": "App\\Controller\\ProjetController::sessionAction"     },     "request_uri": "https://gramc.criann.fr/gramc3/projet/session",     "method": "GET" }
DEBUG10:13:09 | security | Read existing security token from the session.{     "key": "_security_global_security_context",     "token_class": "Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken" }
DEBUG10:13:09 | doctrine | SELECT t0.eppn AS eppn_1, t0.id_individu AS id_individu_2 FROM sso t0 WHERE t0.eppn = ? LIMIT 1[     1 ]
DEBUG10:13:09 | doctrine | SELECT t0.creation_stamp AS creation_stamp_1, t0.nom AS nom_2, t0.prenom AS prenom_3, t0.mail AS mail_4, t0.admin AS admin_5, t0.sysadmin AS sysadmin_6, t0.obs AS obs_7, t0.expert AS expert_8, t0.president AS president_9, t0.desactive AS desactive_10, t0.id_individu AS id_individu_11, t0.id_statut AS id_statut_12, t0.id_labo AS id_labo_13, t0.id_etab AS id_etab_14 FROM individu t0 WHERE t0.id_individu = ? LIMIT 1[     1 ]
DEBUG10:13:09 | security | User was reloaded from a user provider.{     "provider": "App\\Security\\User\\GramcUserProvider",     "username": 1 }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::configure" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\ValidateRequestListener::onKernelRequest" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelRequest".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\SessionListener::onKernelRequest" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::setDefaultLocale".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\LocaleListener::setDefaultLocale" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\RouterListener::onKernelRequest" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\ResolveControllerNameSubscriber::resolveControllerName".{     "event": "kernel.request",     "listener": "Symfony\\Bundle\\FrameworkBundle\\EventListener\\ResolveControllerNameSubscriber::resolveControllerName" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\LocaleListener::onKernelRequest" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleAwareListener::onKernelRequest".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\LocaleAwareListener::onKernelRequest" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener::configureLogoutUrlGenerator".{     "event": "kernel.request",     "listener": "Symfony\\Bundle\\SecurityBundle\\Debug\\TraceableFirewallListener::configureLogoutUrlGenerator" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener::onKernelRequest".{     "event": "kernel.request",     "listener": "Symfony\\Bundle\\SecurityBundle\\Debug\\TraceableFirewallListener::onKernelRequest" }
DEBUG10:13:09 | doctrine | SELECT t0.cle AS cle_1, t0.val AS val_2, t0.id_param AS id_param_3 FROM param t0 WHERE t0.cle = ? LIMIT 1[     "now" ]
DEBUG10:13:09 | doctrine | SELECT t0.cle AS cle_1, t0.val AS val_2, t0.id_param AS id_param_3 FROM param t0 WHERE t0.cle = ? LIMIT 1[     "DateString" ]
DEBUG10:13:09 | doctrine | SELECT t0.cle AS cle_1, t0.val AS val_2, t0.id_param AS id_param_3 FROM param t0 WHERE t0.cle = ? LIMIT 1[     "DateShift" ]
DEBUG10:13:09 | doctrine | SELECT t0.cle AS cle_1, t0.val AS val_2, t0.id_param AS id_param_3 FROM param t0 WHERE t0.cle = ? LIMIT 1[     "NewDate" ]
DEBUG10:13:09 | doctrine | SELECT s0_.type_session AS type_session_0, s0_.hparannee AS hparannee_1, s0_.comm_global AS comm_global_2, s0_.date_debut_session AS date_debut_session_3, s0_.date_fin_session AS date_fin_session_4, s0_.etat_session AS etat_session_5, s0_.id_session AS id_session_6, s0_.id_president AS id_president_7 FROM session s0_ WHERE s0_.etat_session &lt;&gt; ? ORDER BY s0_.id_session DESC[     9 ]
DEBUG10:13:09 | doctrine | SELECT s0_.type_session AS type_session_0, s0_.hparannee AS hparannee_1, s0_.comm_global AS comm_global_2, s0_.date_debut_session AS date_debut_session_3, s0_.date_fin_session AS date_fin_session_4, s0_.etat_session AS etat_session_5, s0_.id_session AS id_session_6, s0_.id_president AS id_president_7 FROM session s0_ WHERE s0_.etat_session &lt;&gt; ? ORDER BY s0_.id_session DESC[     9 ]
INFO10:13:09 | php | User Deprecated: The "Sensio\Bundle\FrameworkExtraBundle\Configuration\Method" annotation is deprecated since version 5.2. Use "Symfony\Component\Routing\Annotation\Route" instead.{     "exception": {} }
DEBUG10:13:09 | event | Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".{     "event": "kernel.controller",     "listener": "Symfony\\Bundle\\FrameworkBundle\\DataCollector\\RouterDataCollector::onKernelController" }
DEBUG10:13:09 | event | Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".{     "event": "kernel.controller",     "listener": "Symfony\\Component\\HttpKernel\\DataCollector\\RequestDataCollector::onKernelController" }
DEBUG10:13:09 | event | Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".{     "event": "kernel.controller",     "listener": "Sensio\\Bundle\\FrameworkExtraBundle\\EventListener\\ControllerListener::onKernelController" }
DEBUG10:13:09 | event | Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".{     "event": "kernel.controller",     "listener": "Sensio\\Bundle\\FrameworkExtraBundle\\EventListener\\ParamConverterListener::onKernelController" }
DEBUG10:13:09 | event | Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".{     "event": "kernel.controller",     "listener": "Sensio\\Bundle\\FrameworkExtraBundle\\EventListener\\HttpCacheListener::onKernelController" }
DEBUG10:13:09 | event | Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".{     "event": "kernel.controller",     "listener": "Sensio\\Bundle\\FrameworkExtraBundle\\EventListener\\TemplateListener::onKernelController" }
DEBUG10:13:09 | event | Notified event "debug.security.authorization.vote" to listener "Symfony\Bundle\SecurityBundle\EventListener\VoteListener::onVoterVote".{     "event": "debug.security.authorization.vote",     "listener": "Symfony\\Bundle\\SecurityBundle\\EventListener\\VoteListener::onVoterVote" }
DEBUG10:13:09 | event | Notified event "debug.security.authorization.vote" to listener "Symfony\Bundle\SecurityBundle\EventListener\VoteListener::onVoterVote".{     "event": "debug.security.authorization.vote",     "listener": "Symfony\\Bundle\\SecurityBundle\\EventListener\\VoteListener::onVoterVote" }
DEBUG10:13:09 | event | Notified event "kernel.controller_arguments" to listener "Symfony\Component\HttpKernel\EventListener\ErrorListener::onControllerArguments".{     "event": "kernel.controller_arguments",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\ErrorListener::onControllerArguments" }
DEBUG10:13:09 | event | Notified event "kernel.controller_arguments" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelControllerArguments".{     "event": "kernel.controller_arguments",     "listener": "Sensio\\Bundle\\FrameworkExtraBundle\\EventListener\\SecurityListener::onKernelControllerArguments" }
DEBUG10:13:09 | event | Notified event "kernel.controller_arguments" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\IsGrantedListener::onKernelControllerArguments".{     "event": "kernel.controller_arguments",     "listener": "Sensio\\Bundle\\FrameworkExtraBundle\\EventListener\\IsGrantedListener::onKernelControllerArguments" }
DEBUG10:13:09 | doctrine | SELECT s0_.type_session AS type_session_0, s0_.hparannee AS hparannee_1, s0_.comm_global AS comm_global_2, s0_.date_debut_session AS date_debut_session_3, s0_.date_fin_session AS date_fin_session_4, s0_.etat_session AS etat_session_5, s0_.id_session AS id_session_6, s0_.id_president AS id_president_7 FROM session s0_ WHERE s0_.etat_session &lt;&gt; ? ORDER BY s0_.id_session DESC[     9 ]
DEBUG10:13:09 | doctrine | SELECT t0.type_session AS type_session_1, t0.hparannee AS hparannee_2, t0.comm_global AS comm_global_3, t0.date_debut_session AS date_debut_session_4, t0.date_fin_session AS date_fin_session_5, t0.etat_session AS etat_session_6, t0.id_session AS id_session_7, t0.id_president AS id_president_8 FROM session t0 ORDER BY t0.id_session DESC
DEBUG10:13:09 | doctrine | SELECT v0_.etat_version AS etat_version_0, v0_.prj_l_labo AS prj_l_labo_1, v0_.prj_titre AS prj_titre_2, v0_.dem_heures AS dem_heures_3, v0_.attr_heures AS attr_heures_4, v0_.politique AS politique_5, v0_.prj_genci_dari AS prj_genci_dari_6, v0_.sond_vol_donn_perm AS sond_vol_donn_perm_7, v0_.penal_heures AS penal_heures_8, v0_.id_version AS id_version_9, v0_.maj_ind AS maj_ind_10, v0_.prj_id_thematique AS prj_id_thematique_11, v0_.prj_id_rattachement AS prj_id_rattachement_12, v0_.id_session AS id_session_13, v0_.id_projet AS id_projet_14 FROM version v0_ INNER JOIN session s1_ ON v0_.id_session = s1_.id_session WHERE (s1_.id_session = ? AND NOT v0_.etat_version = ?)[     null,     10 ]
DEBUG10:13:09 | doctrine | SELECT t0.libelle_thematique AS libelle_thematique_1, t0.id_thematique AS id_thematique_2, t0.id_meta_thematique AS id_meta_thematique_3 FROM thematique t0
DEBUG10:13:09 | doctrine | SELECT t0.libelle_rattachement AS libelle_rattachement_1, t0.id_rattachement AS id_rattachement_2 FROM rattachement t0
CRITICAL10:13:09 | php | Uncaught Error: Call to a member function getIdSession() on null{     "exception": {} }
INFO10:13:09 | php | User Deprecated: The "Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent::getException()" method is deprecated since Symfony 4.4, use "getThrowable()" instead.{     "exception": {} }
INFO10:13:09 | php | User Deprecated: The "Symfony\Component\Debug\Exception\FatalThrowableError" class is deprecated since Symfony 4.4.{     "exception": {} }
INFO10:13:09 | php | User Deprecated: The "Symfony\Component\Debug\Exception\FatalErrorException" class is deprecated since Symfony 4.4, use "Symfony\Component\ErrorHandler\Error\FatalError" instead.{     "exception": {} }
WARNING10:13:09 | app | Error to /gramc3/projet/session{     "exception": {},     "request": {         "attributes": {},         "request": {},         "query": {},         "server": {},         "files": {},         "cookies": {},         "headers": {}     } }
ERROR10:13:09 | app | App\EventListener\ExceptionListener::onKernelException:241 Exception Symfony\Component\Debug\Exception\FatalThrowableError : Call to a member function getIdSession() on null À partir de URL : /projet/session
CRITICAL10:13:09 | request | Uncaught PHP Exception Error: "Call to a member function getIdSession() on null" at /var/www/gramc3/src/Controller/ProjetController.php line 862{     "exception": {} }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::configure" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\ValidateRequestListener::onKernelRequest" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelRequest".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\SessionListener::onKernelRequest" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::setDefaultLocale".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\LocaleListener::setDefaultLocale" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\RouterListener::onKernelRequest" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\ResolveControllerNameSubscriber::resolveControllerName".{     "event": "kernel.request",     "listener": "Symfony\\Bundle\\FrameworkBundle\\EventListener\\ResolveControllerNameSubscriber::resolveControllerName" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\LocaleListener::onKernelRequest" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleAwareListener::onKernelRequest".{     "event": "kernel.request",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\LocaleAwareListener::onKernelRequest" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener::configureLogoutUrlGenerator".{     "event": "kernel.request",     "listener": "Symfony\\Bundle\\SecurityBundle\\Debug\\TraceableFirewallListener::configureLogoutUrlGenerator" }
DEBUG10:13:09 | event | Notified event "kernel.request" to listener "Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener::onKernelRequest".{     "event": "kernel.request",     "listener": "Symfony\\Bundle\\SecurityBundle\\Debug\\TraceableFirewallListener::onKernelRequest" }
DEBUG10:13:09 | event | Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".{     "event": "kernel.controller",     "listener": "Symfony\\Bundle\\FrameworkBundle\\DataCollector\\RouterDataCollector::onKernelController" }
DEBUG10:13:09 | event | Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".{     "event": "kernel.controller",     "listener": "Symfony\\Component\\HttpKernel\\DataCollector\\RequestDataCollector::onKernelController" }
DEBUG10:13:09 | event | Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".{     "event": "kernel.controller",     "listener": "Sensio\\Bundle\\FrameworkExtraBundle\\EventListener\\ControllerListener::onKernelController" }
DEBUG10:13:09 | event | Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".{     "event": "kernel.controller",     "listener": "Sensio\\Bundle\\FrameworkExtraBundle\\EventListener\\ParamConverterListener::onKernelController" }
DEBUG10:13:09 | event | Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".{     "event": "kernel.controller",     "listener": "Sensio\\Bundle\\FrameworkExtraBundle\\EventListener\\HttpCacheListener::onKernelController" }
DEBUG10:13:09 | event | Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".{     "event": "kernel.controller",     "listener": "Sensio\\Bundle\\FrameworkExtraBundle\\EventListener\\TemplateListener::onKernelController" }
DEBUG10:13:09 | event | Notified event "kernel.controller_arguments" to listener "Symfony\Component\HttpKernel\EventListener\ErrorListener::onControllerArguments".{     "event": "kernel.controller_arguments",     "listener": "Symfony\\Component\\HttpKernel\\EventListener\\ErrorListener::onControllerArguments" }
DEBUG10:13:09 | event | Notified event "kernel.controller_arguments" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelControllerArguments".{     "event": "kernel.controller_arguments",     "listener": "Sensio\\Bundle\\FrameworkExtraBundle\\EventListener\\SecurityListener::onKernelControllerArguments" }
DEBUG10:13:09 | event | Notified event "kernel.controller_arguments" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\IsGrantedListener::onKernelControllerArguments".{     "event": "kernel.controller_arguments",     "listener": "Sensio\\Bundle\\FrameworkExtraBundle\\EventListener\\IsGrantedListener::onKernelControllerArguments" }

## Etapes pour reproduire

- Version de gramc v3: feature/criann
- Installation vierge (base de données fraichement installée)
- Se connecter en mode dev (admin admin)
- Aller dans le menu Administrateur
- Cliquer sur le lien "Projets ( par session )"

**Comment by calmip** [comment]
Problème réglé depuis le commit  8f9102a de ce jour
